// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQa3oNro-mEjzFSZZn7XJ3oeePXYuKskI',
    appId: '1:461325044164:web:c46f9f835a4612070fbc91',
    messagingSenderId: '461325044164',
    projectId: 'calendar-alarm-app-405620',
    authDomain: 'calendar-alarm-app-405620.firebaseapp.com',
    storageBucket: 'calendar-alarm-app-405620.appspot.com',
    measurementId: 'G-RLV6N8JTFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEc9pHOZXV3LS2pHtzdPbGR2RxChgx48U',
    appId: '1:461325044164:android:5ee1cec337a922440fbc91',
    messagingSenderId: '461325044164',
    projectId: 'calendar-alarm-app-405620',
    storageBucket: 'calendar-alarm-app-405620.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqKVUeDpV_s7yknhrLuc_pvsJ5Lhn-ARE',
    appId: '1:461325044164:ios:78a9b20a5123d9960fbc91',
    messagingSenderId: '461325044164',
    projectId: 'calendar-alarm-app-405620',
    storageBucket: 'calendar-alarm-app-405620.appspot.com',
    iosClientId: '461325044164-8ijnl4qiknma5e8lesg045us8e8899ur.apps.googleusercontent.com',
    iosBundleId: 'com.example.calendarRise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqKVUeDpV_s7yknhrLuc_pvsJ5Lhn-ARE',
    appId: '1:461325044164:ios:e4f2eacf6e1399970fbc91',
    messagingSenderId: '461325044164',
    projectId: 'calendar-alarm-app-405620',
    storageBucket: 'calendar-alarm-app-405620.appspot.com',
    iosBundleId: 'com.example.calendarRise.RunnerTests',
  );
}
